import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Race Recap: Bahrain - Carnage from Cover to Cover",
    "blurb": "Nothing could have prepared the drivers for the events of last night.",
    "content": [
        rx.vstack(
            rx.text("Bahrain Start", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/bahrain_start.png",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.text(
            r"""Nothing could have prepared the drivers for the events of last night. From Safety Cars to glitches galore, the drivers were faced with perils from before they even got to the paddock all the way through the fireworks.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Interestingly enough, the stewards were a bit unenthused throughout the chaos. But before we get into that and let our illustrious intern unravel the ongoings of last night, there is a bit of late breaking news from the FIA about the race results.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            rx.text("Press Release", as_="span", font_weight="bold"), "", rx.text("For Immediate Release", as_="span", font_weight="bold"), "", rx.text("Date: October 2 2025", as_="span", font_style="italic"),
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Race Results Update:*",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""After reviewing new evidence, the FIA has determined that Red Bull's Brently was wrongly given a 10 second penalty during the second safety car. This penalty led to him finishing in 8th place which has now been corrected to be 4th place with the reduction in finishing time.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""There will be no further room for appeals, but the FIA directors are still open to inquiries or clarifications. For further inquiries or clarification, please contact Erick Tavera or Nick Beglin.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""To all our drivers, it is our responsiblity to ensure a fair and balanced racing environment for all competitors. If there is ever an unprecedented issue within a race, please provide video evidence to the FIA as soon as possible to allow for review of any issues.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Intern Smashing", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/intern_smashing.png",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.text(
            r"""Aaaaaaaaaand with the boring stuff out of the way, let's get into the juicy details of the race and all the gossip around the paddock before hand.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Let's just recap some of the pre-race drama first. The power rankings had Red Bull complaining like they had lost the right to breathe. Maybe don't crash out in Q1 of the first event of the season.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Allegations flew about the Season 3 controversial finale. Teams were yapping about Alpine using controllers to secure their championship or some other kind of fraud.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""But the juicest pre-race gossip is that McLaren's Travis was caught running a livery that did not live up to the FIA's pretentious standards. He ended up serving a race ban instead of serving looks in this throwback livery.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Bahrain Mclaren Livery", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/bahrain_mclaren_livery.png",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.text(
            r"""But it wasn't just the race ban that was juicy, it's the rumors that Papaya Rules may be in play and that Nick may need to sit out all of Miami to ensure a fair battle between the two drivers.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Our paparazzi cornered Nick pre-race and this is what he had to say:""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.box(
            rx.text(
                "\"The situation is a frustrating way to start the championship but I stand with my teammate [and with daddy Zak's Papaya Rules] against the powers that be and hope a resolution can be found quickly.\"",
                color="#CCCCCC",
                font_style="italic",
                font_size="md",
                line_height="1.6",
            ),
            padding_left="16px",
            border_left="4px solid #00b4da",
            margin_y="6",
            width="100%",
        ),
        rx.text(
            r"""With Travis in the timeout corner, drivers started qualifying. Well, most of them did... To recap qualifying, please enjoy this amuse-bouche of memes (wait when did I learn French...)""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Bahrain Qualifying", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/bahrain_qualifying.png",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.text(
            r"""To those who love memes, don't worry there will be more, but my management has asked that I also add "a bit of race recap that has some journalistic integrity," or whatever that means. So read through the next bit or skip to the memes at the bottom if you're more of a picture book kind of adult.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The teammate-less showed out big time in qualifying with Mercedes driver Jayden clutching his first pole of the season and McLaren's Nick completing the front row.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The race got off to a predictably terrible start with Alpine's Eddie absolutely flooring it through Turn 1 forgetting entirely that braking is part of racing. Damage, more damage, and then a tiny bit more damage, occurred in a matter of seconds leading to a Virtual Safety Car right out of the gate.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Once the FIA stopped being the no fun police and let the drivers race again, Nick and Alpine's Joshua got into a side-by-side battle for a lap. The way those two shut up the second they started racing each other was music to the rest of the grid's ears. With them up at the front, the two VCARBs were surprisingly in 3rd and 4th. Rookie Josh helped his teammate create a reasonable gap to the likes of Aston Martin's Del and Ferrari's Erick.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The race continued from there and Patrick has some kind of note about strategies or something stupid like that. I ain't here to write about one-stops vs. two stops vs. whatever the heck some of you did. So let's fast forward a bit. After drivers like Eddie, Aston Martin's Boz, and Mercedes' Jayden and Jairo spent all their time battling back up the ranks, a plague of Safety Cars erupted. I'll let the memes do the rest of the talking though.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Bahrain Race", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/bahrain_race.png",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.text(
            r"""With all the racing said and done, VCARB's Patrick took home the team's first win of the season with a ballsy one-stop strategy and a penalty-less drive. The usual suspects rounded out the podium with Alpine's Joshua and McLaren's Nick standing on the next two steps respectively.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Noteworthy drives came from the two Aston Martins who both battled the mid-field admirably and brought home a strong points haul for their team.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Alpine's Eddie and the Mercedes duo also artificially created noteworthy drives due to their errors, spectacular qualifying, and somehow also lack of qualifying.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The Red Bull team couldn't figure out how to stay out of the limelight either with Matthew finding a sick ramp to do a little trick on mid-race (see below) and Brently practicing his banishing spells on Eddie creating a whole slew of FIA reviews. Both drivers had their positions reinstated, because the FIA is Charmin Ultra Soft when it comes to glitches.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Finally, our Ferrari friends had a bit of a howler with a DNF from Leo and a surprisingly mediocre drive from Erick. I guess there's always next year or whatever the Tifosi say.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Surfer", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/surfer.gif",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
        rx.vstack(
            rx.text("Surfer", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/surfer.gif",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
    ],
    "image": "/thealternativef1-cloudflare/Season4/Images/bahrain_start.png",
    "author": "A Joint Patrick & The Intern Production",
    "date": "October 2, 2025",
    "season": 4,
}
