import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Season 4 Constructor's Power Rankings",
    "blurb": "While the standings are useful, they do not tell the whole story of which teams are trending up throughout the season even without big wins or flas...",
    "content": [
        rx.heading(
            "Preseason Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""While the standings are useful, they do not tell the whole story of which teams are trending up throughout the season even without big wins or flashy moments.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""To kick off the season, the FIA and the race stewards have ranked each team. Initial rankings positioned teams where they finished last season. From there, the results of the preseason race and a few other factors shuffled the order a bit. Not much changed for our top three teams from last season, however Mercedes and Aston Martin both had strong performances, leading to minor shifts in the lower power rankings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""As the season progresses, check back here for more updates on the power rankings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Bahrain Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Red Bull & Mercedes have decided to tango a bit in the mid-field. The teams have swapped back and forth yet again due to the performances from last night's race.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Red Bull primarily benefitted from the FIA removing Brently's penalty and the league reinstating Matthew's finishing point.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Additionally, with strong qualifying and from winning the race, the VCARB team promoted themselves up the rankings. However, this is likely more due to McLaren's lack of a second #1 driver during the race with Travis disqualified by the FIA.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Alpine remains the top contender at this stage even though they are in second overall in the Constructor Standings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Miami Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""After an incredible performance during the sprint, Mercedes had a lack luster outing in the main race. This keeps them low in the power rankings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Red Bull and Ferrari made a swap due to the incredible performance by Brently who is solidifying himself as the team's number one early in the season.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""After the preseason and Bahrain, it seemed the VCARB team had things sorted out and were rocketing towards the top. However, there is a chance they were just a shooting star.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Due to this, as well as having a full line up, McLaren overtakes into second place and nearly dislodges Alpine from their perch atop the rankings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Spain Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""With the first break of the season over, the drivers took Spain's high speed circuit, where tire wear, dirty air, and a whole lot of flare occurred.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Mercedes took home its first full length race win of the season helping them move up in the power rankings. Alpine stays top dog though as McLaren falters and VCARB takes second place back.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""In the midfield, Aston Martin and Ferrari stocks plummet as the teams faced minor setbacks during the race, while Red Bull seemed to have started to get things figured out.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""All in all this was a turbulent race and the power rankings reflect that. In Mexico, expect to see more position swapping here as tire wear is again a major concern going into the race.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Spain Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""With the first break of the season over, the drivers took Spain's high speed circuit, where tire wear, dirty air, and a whole lot of flare occurred.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Mercedes took home its first full length race win of the season helping them move up in the power rankings. Alpine stays top dog though as McLaren falters and VCARB takes second place back.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""In the midfield, Aston Martin and Ferrari stocks plummet as the teams faced minor setbacks during the race, while Red Bull seemed to have started to get things figured out.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""All in all this was a turbulent race and the power rankings reflect that. In Mexico, expect to see more position swapping here as tire wear is again a major concern going into the race.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Baku Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Mercedes is on the rise! Back-to-back wins, both drivers in the Top 5, and some staggering consistency over the last few races has them unanimoulsy voted up another rank from our power rankers.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Alpine jumps back to the top slot as they overtake a slowing VCARB. McLaren began receiving more upward votes this week as well as their top driver began to pursue the podium again.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Further down the field, Red Bull is a casualty of the streaking Mercedes duo. In reality they earned strong votes this week but simply were snuffed out by the rising rookies.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Aston Martin and Ferrari remain where they are at in the rankings, but there are rumblings to have Ferrari overtake Aston Martin if they continue their current trajectory.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Austria (Reverse) Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""The duo at Mercedes has put a signature on the tail end of the first half of the season. Three wins in a row for Jairo and a podium and multiple top 5 finishes for Jaden.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Due to this, they've continued to earn their incredible swing in the power rankings. This also means that someone had to move down in the rankings. This week's victim is last season's runner up, McLaren.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The papaya duo has faced a turbulent start to the season, but whispers around the paddock suggest they may soon lock in with additional practice and new sim racing hardware in hand.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""All the other teams stayed put this week during the power rankings. However, it is likely we see additional shifts in the coming weeks with two sprints on the horizon.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Spa Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""That was quite the race. And the results of the power rankings might suprise a few folks. However, VCARB was unanimously voted the #1 team from the time out in Spa.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Realistically, the Mercedes duo could have been way up there too, but their lack luster performance in the main race set them back.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Alpine seems to have fallen from the power ranker's good graces as they recieved their lowest votes yet.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Other teams remain the same as they performed as expected against their peers during the sprint and race.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Brazil & Austria Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Two races worth of power rankings for the price of one. Last year's title heavy weights have fallen off in the voting during these two rounds of the season.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Both Alpine and McLaren are receiving less and less favorable votes as the season progresses. However, Mercedes continues to rise in the polls.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Both Red Bull and Ferrari have begun to make headway in the rankings as well with Red Bull making it back into 4th and Ferrari finally getting out of last place.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""With five races to go, the rankings are becoming increasingly accurate for the final championship standings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Zadnvoort Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Four races to go and we have a very stable week in the rankings. No shofts across the board. However, Mercedes is still a favorite to take the number #1 spot sometime soon.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The Silver Arrows did not take the lead this week due to a less than nominal performance from Jairo which did not give the committee rationale to propel them over VCARB just yet.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Additionally, with 188 points remaining in the season, teams down to McLaren are still in the hunt mathematically for the championship and more importantly, every single team is still in the race for 2nd and 3rd.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""More on this in an upcoming article about rumors and standings. Stay tuned.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Jeddah & Las Vegas Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""With just two races to go, last week's double header really shook up the power rankings. Teams like Red Bull and VCARB lost out on their previous standings in the rankings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""While teams like Mercedes and Ferrari gained remarkable amounts from the street race showdown.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Alpine and Aston Martin stayed steady in their rankings, but qualifying and other aspects of Aston Martin's outing did make the voting committee consider boosting their position.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Finally, McLaren gained a spot but then levelled off due to a voting gap between Alpine and McLaren.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Abu Dhabi Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""One race left. One more chance to prove the strength of each constructor.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Out in Abu Dhabi the Red Bull team fought back to close the gap on Ferrari. Due to this, they polled higher this week.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Although Red Bull and Ferrari swapped places, the rest of the rankings remained the same.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The VCARB duo and the Mercedes duo are nearly tied for first, but someone must sit on top and so these are the rankings going into the final race of the season.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Monza & End of Season Power Rankings",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""With the finale complete, we set the power rankings to be in line with the final points standings for all of the teams.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Thank you all for enjoying this season with us. Until next time.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
    ],
    "image": "/thealternativef1-cloudflare/Season4/Images/Trophy.png",
    "author": "Patrick",
    "date": "January 24, 2026",
    "season": 4,
}
