import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Season 4 Standings and Rumor Mill Round-Up",
    "blurb": "In this article, The Intern and I will partner once again to deliver a season standings recap as well as some updates to recent rumors from around ...",
    "content": [
        rx.text(
            r"""In this article, The Intern and I will partner once again to deliver a season standings recap as well as some updates to recent rumors from around the paddock. Rumors, as per the usual, will close out the article, so if you are more interested in hot gossip scroll on down and skip the standings summary.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""However, skipping the standings recap would be a real shame, the league has never been more hotly contested with just four races to go. Four teams capable of taking home the Constructor's Championship with all seven still in the running for a podium finish. On the driver side of the championship, there are six drivers still in the hunt for the top crown and only four have been elminiated from contention for a podium finish.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""As this article progresses, please enjoy the memes and commentary from The Intern. As a pair, we will do our best to identify which of us is slandering you so you know who to come for later.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "STANDINGS SUMMARY - CONSTRUCTOR'S CHAMPIONSHIP",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""So, what in the world does this table actually tell you, the reader? First, please read it one column at a time. Each column depicts a winning or best case scenario for each team.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""For instance, let us take a peak at the Red Bull column first. This column displays the highest amount of points that the Red Bull team could achieve in the Red Bull row (275). This means for the dynamic Red Bull duo, the best they can do is second place over all with 1-2 finishes for each of the final races. This can be assessed by comparing their maximum to the current points in the Current Points column. Where negative points are shown in the Red Bull column, those teams are unable to be beaten by Red Bull by that many points. The other point values in the Red Bull column are the points other teams must score less than for Red Bull to achieve their maximum final position.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Now there is one caveat in all of this. The bonus points per race are not accounted for in these calculations. There are 4 bonus points per race, in other words 16 bonus points total, available over the remainder of the season. So, for instance, Brently and Newman could improve their odds down the stretch by bringing home a few fastest laps.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Finally, 188 is the maximum number of points a team could secure (including all the bonus points) per race. With all this explained, below we will dive into each team and their feasible scenarios.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "PODIUM HUNT TEAMS",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.heading(
            "Ferrari",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""The prancing horses theoretically could make their way all the way up the ranks and into third without any bonus points, and even into second with a healthy handful of bonus points.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""However, this requires them to run 1-2 in all four of the final races and for Mercedes, VCARB, and Alpine to have some generational failures filled with DNFs for all three teams.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""It feels moderately unlikely that the scarlett duo will find themselves on the podium steps. But at this point, I cannot, in good conscious, count them out. Crazier things have certainly happened in the world of motorsports.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""On their current trajectory, the betting odds are on the duo finishing in 6th this season with a strong battle against Aston Martin brewing.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Aston Martin",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""The racing green need to find some pace in the coming weeks and similar luck requirements as Ferrari to make the podium. They have marginally better odds though and with a few bonus points really could make their way up the standings.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""With only a 3.5 point lead over Ferrari, there is more than a fair chance for either Aston Martin or Ferrari to finish in 6th. However, the Silverstone based duo has a greater chance of leaping up into 5th place by the time the season finale rolls around.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Betting against a perennial speedster like Del typically proves to be futile. This two team battle for 6th also highlights how powerful last year's mid-season swap that paired Del and Erick could have been had they not found their new teammates.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Red Bull",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""The energy drink duo of Newman and Brently have found themselves as the first team out of contention. With 103 points to date, the team is the highest scoring of our three teams that are officially unable to win the championship.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""However, the effort they have put in so far has given them a straighter fight for 2nd place. They do not need to rely on bonus points to make it to the the second highest step on the podium.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Instead, they need a whole lot of luck and for VCARB to finish with less than 19 points over the next four races. This is obvioulsy unlikely, so what is the betting man's choice for Red Bull?""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""With the papaya team lacking the umph they had last year, it is favorable for Red Bull to make up some ground in these final few races and find themselves in 4th over all. To make this bold prediction stick, the Red Bull squad will need season best performances from both drivers to close the gap and overtake McLaren. Otherwise, they are simply in a great position to defend against late Ferrari and Aston Martin charges.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "McLaren",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""McLaren is a storied team with the most consistent presence at the top. It might all finally come to an end this season. Sitting securely in 4th place in the standings, a minor miracle would be needed to make it all the way to the top.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""However, there is a strong chance that McLaren could bolt all their wheels on and come out a place or two higher in the standings. Alpine does truly need to perform well if McLaren begins to light it up. VCARB cannot rest on their laurels either.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""But it will take an enormous amount of luck and plenty of skill to avoid mishap and make the comeback a reality. The betters out there might, for the first time in this article, consider McLaren's current position as their most likely position.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Alpine",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Last year's controversial champions have found themselves in a tough situation. They have been shocked like the rest of the league by the raw speed the Mercedes duo possess. But that does not mean they are out for the count.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""With a 1-2 finish in every race and a 4-5 finish in each race from the Mercedes duo, the French squad could bring home the championship. This all works out even if their nearest rival, VCARB, finishes 3-6 in each of the final races.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""So it is truly not over yet for the reigning champions. However, with all bets on the table, not too many are favoring the hot pink racers. In fact, in their recent polling in the power rankings, they are squarely settled into 3rd place. Only time will tell if some luck rolls their way.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "VCARB",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""The clearest contender for the crown, outside of the current leader, is VCARB. In fact, they are the only team in the chase with their destiny in their own hands. With a 1-2 finish in each of the final races, no matter how well Mercedes performs, VCARB will take home the shiniest of trophies.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""But that might be a tall order for the team. With a rookie and a three time race winner, pulling in four wins and four second place finishes in sequence might be out of the cards.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""However, this avenue is simply the one they have total control over. With a few DNFs or low point outings from the Mercedes duo and some strong performances from the VCARB brothers, the championship is certainly still on the table.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Betting odds are mixed here, with the team still polling well in power rankings, but still the chasers. Regardless, it is a promising season for the new pair with second year driver and rookie finding their groove throughout the season.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.heading(
            "Mercedes",
            size="4",
            color="#00b4da",
            margin_top="6",
            margin_bottom="3",
            font_family="Outfit"
        ),
        rx.text(
            r"""Truly, there is not much to write here. If this duo performs the way they have throughout the season, they will be the champions at the end of it all. As the only team with a 1-2 finish this season, it is very likely they can repeat that magic.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""Now, of course, a few bad performances in qualifying, or even a DNF or two would shake this rock solid foundation.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.text(
            r"""The odds are truly in Mercedes' favor this late in the season. Again, only time will tell if consistency for the Mercedes team will prevail or will a few untimely errors erode the lead they currently have.""",
            color="#E0E0E0",
            font_size="md",
            line_height="1.7",
            margin_bottom="4",
        ),
        rx.vstack(
            rx.text("Surfer", color="#888888", font_size="xs", margin_bottom="1"),
            zoomable_image(
                src="/thealternativef1-cloudflare/Season4/Images/surfer.gif",
                width="100%",
                max_width="400px",
                border_radius="md",
                box_shadow="0 4px 12px rgba(0,0,0,0.4)"
            ),
            align_items="center",
            width="100%",
            margin_y="4",
        ),
    ],
    "image": "/thealternativef1-cloudflare/Season4/Images/surfer.gif",
    "author": "A Joint Patrick & The Intern Production",
    "date": "December 22, 2025",
    "season": 4,
}
