import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Austria Recap: Absolute Cinema",
    "blurb": "One Sprint, one race, two championships on the line, and an incredible amount of drama.",
    "content": [
rx.vstack(
    rx.text("Austria Race Cover", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Alpine_Braking.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""One Sprint, one race, two championships on the line, and an incredible amount of drama. Austria had it all folks. It was truly one for the ages. All the contenders were there and each of them spiced up the Saturday race with their own extra magic. The hills were certainly alive with the sound of music, and for one driver, the sound of championship celebrations.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""The Red Bull Ring is known for creating perilous moments on track. Drivers are forced to execute along the finest of margins in both the heavy braking zones and the high speed turns and exits. For a league that struggles with keeping it between the white lines, this track only magnifies those mistakes. Ferrari’s Erick took home the crown for most penalties awarded, but still no one has surpassed Alpine’s Eddie’s season high yet. Per the usual, the McLaren’s kept it tidy throughout, while the rest of the field either earned penalties or ended their races prematurely.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""But before we get to the main event, let’s discuss qualifying and the Sprint race. During qualifying spectators were treated to a first time polesitter with Eddie lighting up the timing charts and setting the time to beat. However his Alpine teammate and main contender for the Driver’s World Championship, Joshua, ended up stuck in Q2 for the second time in a row. On his exit from the pit at the start of the session Joshua had a major lapse in talent and ended up pinning his car in the narrowest part of the pitlane exit. This disqualified the driver from continuing, situating him in 15th place on the grid for the Sprint.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Joshua Pit Exit Incident", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Talent.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""At the start of the Sprint, most of the field was up near the front and as the first lap began, some bumping and shoving occurred in both Turn 1 and Turn 3. However, the drivers predominantly remained clean through the first portion of the lap. That was all true until VCARB’s Patrick attempted a daring overtake on Erick into Turn 4, but missed his braking point and ended up in the gravel and losing places to the majority of the field. As the race continued he was able to battle back and switch places with his teammate when a radio call on the penultimate last lap set team orders for the two of them. More notably though is the progress Joshua made from 15th up into 5th. He was able to pass the majority of the field but ran out of laps to make it all the way to the front. His teammate Eddie however, did not have as fortunate of a race, tumbling from pole to 4th place, the first time pole sitter was not able to clutch up this go around.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Ferrari’s new driver Del was able to make gains throughout the Sprint and battled with McLaren’s Nick for first and ultimately won the race, with Nick and Erick just behind. The battle at the front led to a busy post-Sprint media room where drivers were heard bickering about how to best conserve battery, make overtakes, and ultimately win the race at the Red Bull Ring.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""With tensions high, no one expected all the drama that the main event would bring. After setting the reverse grid, drivers waited for the lights to go out, and when they did, chaos ensued. Drivers were launched off the track in Turn 1, some perilously plummeting behind the rest of the field, with others damaged and in need of a pitstop. Because of the mass chaos, the race director determined a full restart with enough time to repair minor damage was the right call. The race was red flagged and the drivers returned to the grid for another start. This go around, with much more caution, and a heightened sensitivity to the turmoil that could occur in Turn 1, most drivers decided to safely play out the first few corners.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""It is important to stress that while most drivers proceeded with caution, the Alpine duo had other ideas. To better illuminate their decision making, along with subsequent events of the race, we have requested that the intern take over for the remainder of this article.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""THAT’S RIGHT FOLKS, STRAP IN FOR SOME ROASTS BECAUSE THERE IS NO OTHER WAY TO HANDLE WHAT HAPPENED NEXT.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""I call this the roast of Joshua & Eddie’s braking abilities: > You know, they say racing is 90% mental. In Joshua's case, it's more like 90% \"Where's the brake pedal?\"""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""I heard Eddie is thinking of switching careers... to a crash test driver. At least then he'd have an excuse for not stopping in time.""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""What's Joshua's favorite song? \"Oops, I Did It Again!\"""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""Eddie's braking technique is so innovative, they're calling it \"The Scenic Route.\"""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""You know, they say experience is the best teacher. Joshua has a PhD in \"Overshooting Corners.\"""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""Eddie's braking points are like a unicorn – mythical and never seen.""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""The duo’s absolute inability to brake caused some incredibly sketchy moments. Erick put on his best impression of Evel Knievel and got his entire car airborne when he had to avoid and evade the Alpine mess.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Erick Airborne in Austria", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Erick_Airborne.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""It was honestly a nightmare for the first few laps and I discovered a new ick: boys who can’t brake. No cap, it got worse. After the Alpines caused enough of a traffic jam, drivers began to spread out and overtake one another. Remember, the whole league started in the back of the grid and had a lot of ground to make up on the AI.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""As drivers began to pass the AI, something I can only describe as sudo-Imperial Japan occurred on track. Alex Albon could not fathom being passed by a VCARB and so he kamikazed it straight into the back of Patrick, causing a major accident and ending his race entirely.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Albon Kamikaze on Patrick", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Kamikaze.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""But the AI weren’t satisfied with only taking out Patrick. They also took out Eddie later in the race just as everyone’s strategies were starting to heat up. This allowed for some incredibly late pitstops for some drivers such as Erick and VCARB’s Brently. Erick took the pitstop in the hopes that his pitcrew would let him serve his penalties, however, we’re talking about Ferrari. The clown meme is so tired so please enjoy this classic instead.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Erick Ferrari Strategy Meme", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Erick.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""But Brently on the other hand put on a masterclass. Even Mad Max hasn't shown this kind of comeback in a long time. From last place, Brently became the smoothest operator of all time and torched the field on new hards, landing himself just a few seconds shy of a podium finish in fourth. The GOAT Lightning McQueen called and said I had to use this meme for him.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Brently Lightning McQueen Performance", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/thealternativef1-cloudflare/Season3/Images/Austria_Brently.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""Up at the front we saw Joshua and Nick duking it out for the win. But it was too little too late for Joshua. Even with the win, Nick still gapped him in the championship standings and took home his third consecutive Driver’s World Championship. And with that I cede my keyboard to Patrick to close this one out.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""With the Driver’s Champion crowned, and second place nearly locked for Joshua, the Ferrari and VCARB saga will be the focus of the final race of the season. Both teams could end up in third in the Constructor’s Championship, and all four drivers could end up in third in the Driver’s Championship. Alpine and McLaren will also need to finish their bout on the track to find out who will win the Constructor’s Championship. Stay tuned for a special post from McLaren and the final Race Week Update focused on COTA.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
    ],
    "image": "/thealternativef1-cloudflare/Season3/Images/Austria_Alpine_Braking.png",
    "author": "A Joint Patrick & The Intern Production",
    "date": "February 10, 2025",
    "season": 3,
}
