import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "INSIDER SCOOP: ***Alpine's Plight***",
    "blurb": "It comes at no surprise to those that have followed the league this season that Alpine has fumbled one championship and depending on how COTA pans ...",
    "content": [
rx.text(
    r"""It comes at no surprise to those that have followed the league this season that Alpine has fumbled one championship and depending on how COTA pans out, potentially two. Our reporters were able to catch up with team officials and both drivers about the future of the team.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Alpine's future in Formula 1 may face significant uncertainty if they fail to secure a top spot in the Constructors' Championship this season. Their main driver, Joshua Rosario, has expressed concerns that the team’s lack of progress could force him to seek opportunities elsewhere. With aspirations of competing at the front of the grid, Joshua’s loyalty to Alpine is tied to their ability to improve their performance, making it clear that a poor showing in the Constructors' standings could lead to a departure as he looks for a team with better championship prospects. In reference to the Constructor’s Championship, Joshua directly responded with:""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""If we lose, I’m gone.""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""But beyond the championship, it appears that tensions are at their highest with the talented young duo at each other's throats. An exchange between the two drivers was recently overheard by our reporting team and has been transcribed here.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""Are you staying on the team? - Joshua""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""What team? - Eddie""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""Alpine! - Joshua""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""I don’t know... - Eddie""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.box(
    rx.text(
        r"""You’re useless to me. - Joshua""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""The duo’s bickering has been a point of contention throughout the final races of the season. However, it has never appeared this likely that the duo would break up. With the impending offseason and silly season around the corner, it's likely we see many exits from discontent drivers and teammates.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
    ],
    "image": "/thealternativef1-cloudflare/Season3/Images/Trophy.png",
    "author": "Insiders: Joshua, Eddie, & Patrick",
    "date": "February 11, 2025",
    "season": 3,
}
