import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Race Week - Baku",
    "blurb": "It has been an eventful few days since the league’s first Sprint race.",
    "content": [
rx.text(
    r"""It has been an eventful few days since the league’s first Sprint race. A major FIA decision was made that changed the results of the race, and let’s just say there has not been this much rioting since the 1991 Chicago Bulls celebration riots. Some drivers put pen to paper to rip into the FIA’s decision for being abrupt and unfair. While other drivers defended the decision as it upheld aspects of racing sportsmanship they appreciate. Alpine’s start driver Joshua ended his tirade by saying:""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""This is really BS and unfair. - Joshua""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""The next day, Joshua spoke to a local reporter and stated:""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""Everyone better watch out because we are coming for blood [in Baku]. [The decision is] Not fair but we move forward. - Joshua""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""His teammate Eddie took an interview with a Houston based reporter where he labelled the FIA as blind while elaborating on the situation between he and Joshua:""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""While yes I do admit to running Josh off the road, which I did get a penalty for on top of my other 5-grid penalty (which resulted in me having a 10-grid penalty already), Joshua also got a 5-grid penalty from that for no exact reason. Due to the FIA not having eye balls, Joshua already had to push harder and try stupider sht just to make it back to his true position, P1. This all resulted in his situation during the Sprint race. He should not be penalized further, when he was already penalized and is getting penalized for a rule which was never stated before the race. - Eddie""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""Other drivers like the VCARB pair were more ceremonious and in agreement with the FIA’s decision. Patrick was heard screaming, “I’m a winner!” as far away as Erick’s house. The shouts were measured on local seismology equipment as a 3.2 magnitude earthquake on the Richter Scale. His teammate Brently was more subdued with his commentary stating:""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.box(
    rx.text(
        r"""I feel like it was the right decision. As it seemed odd when and where he retired [in the Sprint]. - Brently""",
        color="#CCCCCC",
        font_style="italic",
        font_size="md",
        line_height="1.6",
    ),
    padding_left="16px",
    border_left="4px solid #00b4da",
    margin_y="6",
    width="100%",
),
rx.text(
    r"""Multiple teams have also released formal statements which can be found at the end of this article. More importantly, this ruling shakes up the standings quite a bit. Joshua dropped below McLaren’s Nick in the Driver’s Championship and VCARB closed even further on McLaren in the Constructor’s Championship.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""With all this said, it’s time to focus on the upcoming street race in Baku. Drivers will be met with close walls, the longest pedal to the metal straight on the calendar, and deviously challenging combinations of undulation and corners. Sector 1 is essentially three flatout straights with ninety-degree left turns at the end of each. If drivers survive that, they will quickly find themselves at the beginning of the most challenging sector on the league’s calendar. The castle section and Turn 15 have caught out many talented drivers before and are certainly capable of wreaking havoc on the race this week. Sector 3 is a drafters paradise, but the exit of Turn 16 will make or break any challenger’s attack on their rivals.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Baku City Circuit Map", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/Season3/Images/Baku_Circuit.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""This will be the league’s first race in Azerbaijan. With plenty of treacherous turns and a great passing opportunity at the end of the front straight, the Baku street circuit will certainly test the league’s fortitude. Especially when one considers the embers that are ready to be stoked by even the slightest breeze from China’s incident.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    rx.text("Official Team Statements", as_="span", font_weight="bold"),
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.flex(
    zoomable_image(src="/Season3/Images/China_Alpine_Statement.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_Red_Bull_Statement1.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_Red_Bull_Statement2.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_VCARB_Statement.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_Ferrari_Statement.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_Aston_Martin_Statement.png", width="150px", margin="2"),
    zoomable_image(src="/Season3/Images/China_McLaren_Statement.png", width="150px", margin="2"),
    flex_wrap="wrap",
    justify="center",
    width="100%",
    margin_y="4",
),
    ],
    "image": "/Season3/Images/Baku_Circuit.png",
    "author": "Patrick Knowles",
    "date": "January 11, 2025",
    "season": 3,
}
