import reflex as rx
from the_alternative_f1.articles.components import zoomable_image

article = {
    "title": "Standings Update",
    "blurb": "Does anyone hear that.",
    "content": [
rx.text(
    r"""Does anyone hear that? That muffled beat? Oh no...they're back...""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    rx.text("***Fetty Wap continues to blare in the background***", as_="span", font_style="italic"),
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""That's right folks, I am back and better than ever. I heard you all were looking for a standings update. Now, I told Patrick I would do this on one condition, I get paid stacks. Which he refused. So I countered and asked if I could be as unhinged as I wanted when rating and ranking each driver’s and team’s chances. Which he begrudgingly accepted. So go get your blanky and snuggle up with whoever helps you stop crying, because I ain’t holding back.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""My boss said I had to do a formal writeup of each team and driver, which for once I listened to and did. But it's the worst. So please enjoy the collection of memes below that detail each driver’s and team’s championship odds.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Drivers and Teams Championship Odds", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/Season3/Images/Standings_Memes.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    rx.text("Driver’s Championship", as_="span", font_weight="bold", font_style="italic"),
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Let’s start it off right and talk about our top individual award for the season, the Driver’s Championship. There are a maximum of 96 points left for one person to score. Two Sprints, three races, and five fastest laps. That means anyone currently with less than 100 points is not gonna be a winner. So I am not even going to waste another second on Patrick, Brently, Del, Eddie, Zane, Yeti, Boz, Travis, or Gary. “But wait, they could still get second or third,” man shush, who cares about first loser and second loser. All that matters is the top step on the podium. Which means Erick, Joshua, and Nick are the only three left who can take home the trophy. So how can each driver do it?""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""All Nick has to do is not choke. That’s it. Don’t choke. It's not that hard, man. Straight up, if Nick stays on the podium for all three races and gets 5th or better in the two Sprints, it's over for Joshua and Erick. We’re talking about the guy whose average finishing position is 1.6… It really feels like he’s got this in the bag. If he wins just one more race and gets a fastest lap, all he has to do is finish 9th or better in the remaining events. He has this on lock. So no pressure dude. Three time champion has a nice ring, however, Joshua has a legitimate chance, and well…Erick…he can technically win.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Joshua simply needs to win. Win, win, win. Well, actually I forgot one thing. Since this guy forgot to show up for a few races, now he also has to pray for Nick to make a mistake. So really Joshua’s strategy is win, win, win, pray, and maybe send Nick into the wall. Again, it's not that hard, but ever since he got his wheel there has been a severe drop off in performance and attendance. So maybe it will be a challenge? Or maybe he will quit in Austria after trying to kill Nick like we saw with Max and Lando earlier this year.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Now for Erick the road to the championship is actually quite challenging and convoluted. From my perspective he is out of the running, but the math says there’s a chance.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("So You're Telling Me There's A Chance", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/Season3/Images/Chance.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    r"""Erick actually does have to win out. Where Joshua has some room based on how Nick performs, Erick has no wiggle room. If he wins two races, both Sprints, gets second in the third race, and has all five fastest laps, he will end up 1 point short of where Nick will finish if Nick simply does not show up. Yikes. So, technically, there’s a chance, but the vibes in the studio say he is likely playing for second fiddle.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""The rest of y’all are just praying for a giant meteor to whipe out the drivers in front of you.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.vstack(
    rx.text("Championship Meteor Scenario", color="#888888", font_size="xs", margin_bottom="1"),
    zoomable_image(
        src="/Season3/Images/Meteor.png",
        width="100%",
        max_width="400px",
        border_radius="md",
        box_shadow="0 4px 12px rgba(0,0,0,0.4)"
    ),
    align_items="center",
    width="100%",
    margin_y="4",
),
rx.text(
    rx.text("Constructor’s Championship", as_="span", font_weight="bold", font_style="italic"),
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Now I wanted to say all hope is not lost for all of you in the Constructor’s Championship, but for one team, the math says it's over. The storied energy drink team has had some tough sledding this year and even if Boz and Yeti pull off the miracle of back-to-back-to-back-to-back-to-back 1-2s in all the races and Sprints remaining with five fastest laps, they will end 10 points shy of McLaren if they simply don’t show up. Therefore, with all due respect, gentlemen of Red Bull, “you’re fired.”""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""For the rest of y’all, you’ve got a chance, even if it is a miniscule one. New look Aston Martin will really need to pull in some incredible points hauls with Zane and Gary going absolutely ballistic to take home the championship. Even Ferrari down in fourth needs to have an incredible turn around with their new driver pairing. So let’s focus on our current top three, McLaren, Alpine, and VCARB.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""I think we all know what McLaren needs to do, win. The only thing that could really stop them is if the Alpine drivers decide to stop bickering and actually work together. If one McLaren driver wins out with the fastest laps and the other DNFs, the Alpine duo can take home the championship by placing 2nd and 4th in every race, winning by just 3 points. So McLaren does have to show out, but if both McLaren drivers finish and one wins out with the fastest laps, there is no possible way for Alpine to catch up.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""So how does Alpine win? Well they either outplace both McLarens by a couple places, or they learn how to effectively sabotage. Neither of which seem all that likely as we have watched Eddie try to sabotage Erick all season with no success. But the team still is in the hunt and if McLaren even slightly missteps, Alpine will likely take home the championship.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
rx.text(
    r"""Now the VCARB bozos have a slim shot at victory here. Technically they, like Ferrari and Aston Martin, are still in the hunt. But they need to really show up and show out, and maybe even pray for some chaos with Alpine and McLaren. We’re talking double podium finishes at every race with McLaren and Alpine crashing each other out a couple of times.""",
    color="#E0E0E0",
    font_size="md",
    line_height="1.7",
    margin_bottom="4",
),
    ],
    "image": "/Season3/Images/Standings_Memes.png",
    "author": "The Intern",
    "date": "February 4, 2025",
    "season": 3,
}
