from the_alternative_f1.articles.Season5.Grid_Announcements.Haas import article as Haas_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Erick import article as Erick_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.RedBull import article as RedBull_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Cadillac import article as Cadillac_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Ferrari import article as Ferrari_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.McLaren import article as McLaren_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Williams import article as Williams_Article
from the_alternative_f1.articles.Season5.Tracks.Rankings import article as Rankings_Article
from the_alternative_f1.articles.Season5.Tracks.Schedule import article as Schedule_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Audi import article as Audi_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.Mercedes import article as Mercedes_Article
from the_alternative_f1.articles.Season5.Grid_Announcements.TheGrid import article as TheGrid_Article
from the_alternative_f1.articles.Season5.Preseason.PreseasonArticle import article as Preseason_Article
from the_alternative_f1.articles.Season5.Preseason.MexicoRecap import article as Mexico_Recap_Article
from the_alternative_f1.articles.Season5.Preseason.VegasRecap import article as Vegas_Recap_Article
from the_alternative_f1.articles.Season5.TrophyReveal.TrophyTeaser import article as TrophyTeaser_Article
from the_alternative_f1.articles.Season5.Preseason.HungaryRecap import article as Hungary_Recap_Article
from the_alternative_f1.articles.Season5.TrophyReveal.TrophyReveal import article as TrophyReveal_Article

season = {
    "season_number": 5,
    "sheet_name": "Season5",
    "schedule_sheet": "S5Schedule",

    # Rookies: drivers not present in Season 4
    "rookies": {"Grayson", "Josh C.", "Randy", "Evelo"},

    "articles": [TrophyReveal_Article, Hungary_Recap_Article, TrophyTeaser_Article, 
    Vegas_Recap_Article, Mexico_Recap_Article, Preseason_Article, 
    TheGrid_Article, Mercedes_Article, Audi_Article,
    Schedule_Article, Rankings_Article, Williams_Article, 
    McLaren_Article, Ferrari_Article, Cadillac_Article, 
    RedBull_Article, Erick_Article, Haas_Article],

    "team_colors": {
        "Ferrari": "red",
        "McLaren": "#FF6A00",
        "Red Bull": "darkblue",
        "Mercedes": "black",
        "Haas": "white",
        "Audi": "#A33E2C",
        "Cadillac": "#FFEA00",
        "Williams": "DodgerBlue",
    },

    "driver_colors": {
        "Joshua": "darkblue",
        "Eddie": "#8888c9",
        "Nick": "#FF6A00",
        "Del": "#FFAE00",
        "Patrick": "#FFEA00",
        "Josh": "#A8A153",
        "Matthew": "white",
        "Brently": "#C5C5C5",
        "Grayson": "DodgerBlue",
        "Josh C.": "#99ccff",
        "Boz": "#A33E2C",
        "Evelo": "#9E6156",
        "Jaden": "red",
        "Leo": "#ff6060",
        "Jairo": "black",
        "Randy": "#909090",
    },

    "super_license_points": {
        "Joshua":   [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Eddie":    [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Nick":     [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Del":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Patrick":  [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Josh":     [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Matthew":  [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Brently":  [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Grayson":  [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Josh C.":  [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Boz":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Evelo":    [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Jaden":    [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Leo":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Jairo":    [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "Randy":    [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    },

    "preseason_power_rankings": [
        "McLaren",
        "Cadillac",
        "Red Bull",
        "Ferrari",
        "Mercedes",
        "Haas",
        "Williams",
        "Audi",
    ],

    "preseason_races": [
        {
            "name": "Pre-Season: Mexico",
            "results": [
                {
                    "place": "1",
                    "driver": "Joshua",
                    "team": "Red Bull",
                    "qualifying": "1",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "2",
                    "driver": "Nick",
                    "team": "McLaren",
                    "qualifying": "3",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "Yes",
                },
                {
                    "place": "3",
                    "driver": "Jaden",
                    "team": "Ferrari",
                    "qualifying": "5",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "4",
                    "driver": "Patrick",
                    "team": "Cadillac",
                    "qualifying": "8",
                    "FL": "-",
                    "DOTD": "Yes",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "5",
                    "driver": "Matthew",
                    "team": "Haas",
                    "qualifying": "4",
                    "FL": "Yes",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "6",
                    "driver": "Leo",
                    "team": "Ferrari",
                    "qualifying": "7",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "7",
                    "driver": "Del",
                    "team": "McLaren",
                    "qualifying": "DNS",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "Y",
                    "CD": "-",
                },
                {
                    "place": "8",
                    "driver": "Eddie",
                    "team": "Red Bull",
                    "qualifying": "10",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "9",
                    "driver": "Evelo",
                    "team": "Audi",
                    "qualifying": "12",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Jario",
                    "team": "Mercedes",
                    "qualifying": "2",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Brently",
                    "team": "Haas",
                    "qualifying": "9",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DSQ",
                    "driver": "Randy",
                    "team": "Mercedes",
                    "qualifying": "11",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DSQ",
                    "driver": "Josh",
                    "team": "Cadillac",
                    "qualifying": "6",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
            ]
        },
        {
            "name": "Pre-Season: Vegas",
            "results": [
                {
                    "place": "1",
                    "driver": "Joshua",
                    "team": "Red Bull",
                    "qualifying": "1",
                    "FL": "Yes",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "2",
                    "driver": "Jairo",
                    "team": "Mercedes",
                    "qualifying": "12",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "3",
                    "driver": "Nick",
                    "team": "McLaren",
                    "qualifying": "4",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "Yes",
                },
                {
                    "place": "4",
                    "driver": "Patrick",
                    "team": "Cadillac",
                    "qualifying": "6",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "5",
                    "driver": "Del",
                    "team": "McLaren",
                    "qualifying": "13",
                    "FL": "-",
                    "DOTD": "Yes",
                    "MOT": "Yes",
                    "CD": "-",
                },
                {
                    "place": "6",
                    "driver": "Josh",
                    "team": "Cadillac",
                    "qualifying": "5",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "7",
                    "driver": "Leo",
                    "team": "Ferrari",
                    "qualifying": "3",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Boz",
                    "team": "Audi",
                    "qualifying": "14",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Jaden",
                    "team": "Ferrari",
                    "qualifying": "2",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Brently",
                    "team": "Haas",
                    "qualifying": "10",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DSQ",
                    "driver": "Evelo",
                    "team": "Audi",
                    "qualifying": "11",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
            ]
        },
        {
            "name": "Pre-Season: Hungary Sprint",
            "results": [
                {
                    "place": "1",
                    "driver": "Jaden",
                    "team": "Ferrari",
                    "qualifying": "2",
                },
                {
                    "place": "2",
                    "driver": "Joshua",
                    "team": "Red Bull",
                    "qualifying": "1",
                },
                {
                    "place": "3",
                    "driver": "Nick",
                    "team": "McLaren",
                    "qualifying": "3",
                },
                {
                    "place": "4",
                    "driver": "Patrick",
                    "team": "Cadillac",
                    "qualifying": "4",
                },
                {
                    "place": "5",
                    "driver": "Josh",
                    "team": "Cadillac",
                    "qualifying": "6",
                },
                {
                    "place": "6",
                    "driver": "Brently",
                    "team": "Haas",
                    "qualifying": "5",
                },
                {
                    "place": "7",
                    "driver": "Matthew",
                    "team": "Haas",
                    "qualifying": "9",
                },
                {
                    "place": "8",
                    "driver": "Boz",
                    "team": "Audi",
                    "qualifying": "10",
                },
                {
                    "place": "9",
                    "driver": "Evelo",
                    "team": "Audi",
                    "qualifying": "8",
                },
                {
                    "place": "10",
                    "driver": "Randy",
                    "team": "Mercedes",
                    "qualifying": "7",
                },
            ]
        },
        {
            "name": "Pre-Season: Hungary",
            "results": [
                {
                    "place": "1",
                    "driver": "Joshua",
                    "team": "Red Bull",
                    "qualifying": "9",
                    "FL": "Yes",
                    "DOTD": "Yes",
                    "MOT": "Yes",
                    "CD": "-",
                },
                {
                    "place": "2",
                    "driver": "Josh",
                    "team": "Cadillac",
                    "qualifying": "6",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "3",
                    "driver": "Matthew",
                    "team": "Haas",
                    "qualifying": "4",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "4",
                    "driver": "Patrick",
                    "team": "Cadillac",
                    "qualifying": "7",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "5",
                    "driver": "Nick",
                    "team": "McLaren",
                    "qualifying": "8",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "6",
                    "driver": "Leo",
                    "team": "Ferrari",
                    "qualifying": "11",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "Yes",
                },
                {
                    "place": "7",
                    "driver": "Del",
                    "team": "McLaren",
                    "qualifying": "12",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "8",
                    "driver": "Brently",
                    "team": "Haas",
                    "qualifying": "5",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "9",
                    "driver": "Boz",
                    "team": "Audi",
                    "qualifying": "3",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "10",
                    "driver": "Evelo",
                    "team": "Audi",
                    "qualifying": "2",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Jaden",
                    "team": "Mercedes",
                    "qualifying": "10",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
                {
                    "place": "DNF",
                    "driver": "Randy",
                    "team": "Mercedes",
                    "qualifying": "1",
                    "FL": "-",
                    "DOTD": "-",
                    "MOT": "-",
                    "CD": "-",
                },
            ]
        },    
    ],
    "postseason_races": [],
}


